// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230523131745_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Budget", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_id"));

                    b.Property<decimal>("acao_codigo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("acao_nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("ano_movimentacao")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("categoria_economica_codigo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("categoria_economica_nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("credor_codigo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("credor_nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("elemento_codigo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("elemento_nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("empenho_ano")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("empenho_modalidade_codigo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("empenho_modalidade_nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("empenho_numero")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("fonte_recurso_codigo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("fonte_recurso_nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("funcao_codigo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("funcao_nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("grupo_despesa_codigo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("grupo_despesa_nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("indicador_subempenho")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("mes_movimentacao")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("modalidade_aplicacao_codigo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("modalidade_aplicacao_nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("modalidade_licitacao_codigo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("modalidade_licitacao_nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("orgao_codigo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("orgao_nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("programa_codigo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("programa_nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("subelemento_codigo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("subelemento_nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("subempenho")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("subfuncao_codigo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("subfuncao_nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("unidade_codigo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("unidade_nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("valor_empenhado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("valor_liquidado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("valor_pago")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("_id");

                    b.ToTable("Budgets");
                });
#pragma warning restore 612, 618
        }
    }
}
